### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by shincho0922** [shincho0922/furima-34861#12]
#URL
https://furima-34861.herokuapp.com/

#Basic認証のIDとパスワード
ID: admin
Pass: 2222

#出品者用のメールアドレスとパスワード
メールアドレス:  abc@gmail.com
パスワード: abc1234

#購入者用のメールアドレスとパスワード
メールアドレス:  def@gmail.com
パスワード: def1234

**Comment by snkw-works** [comment]
@shincho0922 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [x] **商品が出品されていない状態では、ダミーの商品情報が表示されるようにしましょう**
今回、商品が出品された状態でご提出いただいたため、こちらの項目が確認できませんでした。次回ご提出時にはデータベースをリセットした状態でご提出くださいますよう、よろしくお願いいたします。（詳細はカリキュラムをご確認ください。）

- [x] **ログアウト状態のユーザーでも、商品詳細表示ページを閲覧できるよう修正しましょう**
現状、ログアウト状態のユーザーは商品詳細表示ページを閲覧できない状態です。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by shincho0922** [comment]
指摘事項改善致しましたのでご確認ください

**Comment by snkw-works** [comment]
@shincho0922 さん、再度ご提出いただきありがとうございます‼︎
動作の確認をしたところ、
> 商品が出品されていない状態では、ダミーの商品情報が表示されるようにしましょう

こちらについては確認ができました。ありがとうございます。
引き続き、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [ ] **ログアウト状態のユーザーでも、商品詳細表示ページを閲覧できるよう修正しましょう**
現状、ログイン状態でもログアウト状態でも、詳細ページに遷移しようとするとエラー画面に遷移してしまいます。
<img width="696" alt="スクリーンショット 2021-04-05 11 00 59" src="https://user-images.githubusercontent.com/54050089/113551024-fb143680-962e-11eb-8288-060a3efd403e.png">

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by shincho0922** [comment]
修正いたしましたのでご確認お願いします

**Comment by keisukekodama** [comment]
@shincho0922 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/44963290/100499353-377ce500-31ac-11eb-87cc-2f4bfe1d4012.png)
